### ISSUE TITLE
Out of curiosity: What do you add jupyterlab and syncthing for?

### ISSUE THREAD

**Issue by gitwittidbit** [ai-dock/base-image#6]
Hi, 

I'm new to image generation on my own machine. And I'm wondering what jupyterlab and syncthing are good for. Don't get me wrong, I know and use both apps independently, but I don't get what the point of adding them to forge or invoke or comfyui.

So, just asking out of curiosity.

If I have no use for them, is there a way to deactivate them?

Thanks

**Comment by robballantyne** [comment]
They're added because these images are specifically designed to run on cloud platforms where those apps are useful.  Disable by specifying `SUPERVISOR_NO_AUTOSTART=jupyter,syncthing`

Soon these images will be broken up into the component pieces so they are more suitable for 'normal' docker environments
